name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@master
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag mattlu/sphinx-doc-export:latest
    - name: Push the latest Docker image
      run: docker push mattlu/sphinx-doc-export:latest
